#!/bin/sh

set -e

export VAULT_ADDR=http://127.0.0.1:8200

vault login -method=ldap username=alice password=P@ssword1

vault list secret

vault list secret/security

vault read secret/security/my-secret

vault list secret/engineering

vault read secret/engineering/my-application

vault login -method=ldap username=bob password=P@ssword1

vault write secret/engineering/new-application my-value=some-value

exit 0