#!/bin/sh

set -e

export VAULT_ADDR=http://127.0.0.1:8200
export VAULT_TOKEN=root


cat <<EOF > /tmp/policies/my-application-policy.hcl
path "ad/creds/my-application" {
  capabilities = ["read"]
}
EOF

vault policy write my-application /tmp/policies/my-application-policy.hcl

vault write auth/ldap/groups/engineering policies=security,my-application

exit 0